### PR TITLE
feature add noExecutionDelay option for Player.

### PR DESCRIPTION
**Pull request by Naeemo**
Ensure that svga can be played without delay, discussed in #22.

Signed-off-by: naeemo <370552604@qq.com>

### CODE REVIEW

**Comment by lijialiang** [comment]
The testcase is great 👍🏼, but I have a problem that I am more worried about, which is the performance consumption caused by repeatedly creating `webworker`. Do you have any good suggestions for this?

**Comment by Naeemo** [comment]
Thanks for your quick reply.
I can move the creation of `webworker` out of the running process, ignore the `noExecutionDelay`'s changes during playing, thus avoid `webworker`'s repeatedly termination and creation.
___
Off topic: If we refactor the worker used by the parser, maybe a unified `webworker` is possible. But that's beyond this PR now.

**Comment by lijialiang** [comment]
OK, can you update the submission, we can better understand your attention through the code.

**Comment by lijialiang** [comment]
Regarding the parser and renderer sharing webworker, I actually don't want to do this, mainly because the parsing and rendering are independent of each other. 

The user can use the two parts independently, if the webworker is shared, it will bring coupling logic.

If you have a better idea about this, you are very welcome to open an issue and we will continue to discuss it.

**Comment by Naeemo** [comment]
> OK, can you update the submission, we can better understand your attention through the code.

I force pushed yesterday, only `core/player/animator.ts` was different from initial commit.

**Comment by lijialiang** [comment]
Sorry for the late reply, there is no problem with the test performance, thank you very much for your PR :)

**Comment by lijialiang** [comment]
We have included this change in version `1.5.0-beta.4` and will be released to the official version later. 

Thank you very much again for your PR.

**Pull request merged**
